// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.kone.pbdemo.protocol;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Para_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Para_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Para2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Para2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\010protocol\032\033google/protob" +
      "uf/empty.proto\"\024\n\004Para\022\014\n\004cert\030\001 \001(\t\"\024\n\005" +
      "Para2\022\013\n\003arr\030\001 \001(\0142\303\001\n\rTestCertChain\022;\n\017" +
      "getIdentityCert\022\026.google.protobuf.Empty\032" +
      "\016.protocol.Para\"\000\022<\n\020getX509CertChain\022\026." +
      "google.protobuf.Empty\032\016.protocol.Para\"\000\022" +
      "7\n\021generateSignature\022\017.protocol.Para2\032\017." +
      "protocol.Para2\"\000B&\n\030com.kone.pbdemo.prot" +
      "ocolP\001Z\010protocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_protocol_Para_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Para_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Para_descriptor,
        new java.lang.String[] { "Cert", });
    internal_static_protocol_Para2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_Para2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Para2_descriptor,
        new java.lang.String[] { "Arr", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
