// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.kone.pbdemo.protocol;

public interface Para2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.Para2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes arr = 1;</code>
   * @return The arr.
   */
  com.google.protobuf.ByteString getArr();
}
