// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.kone.pbdemo.protocol;

public interface ParaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.Para)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cert = 1;</code>
   * @return The cert.
   */
  java.lang.String getCert();
  /**
   * <code>string cert = 1;</code>
   * @return The bytes for cert.
   */
  com.google.protobuf.ByteString
      getCertBytes();
}
